from PySide import QtCore, QtGui

class Ui_AppMainWindow(object):
    def setupUi(self, AppMainWindow):
        AppMainWindow.setObjectName("AppMainWindow")
        AppMainWindow.resize(319, 398)
        self.centralWidget = QtGui.QWidget(AppMainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.widget = QtGui.QWidget(self.centralWidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 297, 374))
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtGui.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.LV_hostList = QtGui.QListView(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LV_hostList.sizePolicy().hasHeightForWidth())
        self.LV_hostList.setSizePolicy(sizePolicy)
        self.LV_hostList.setMaximumSize(QtCore.QSize(150, 200))
        self.LV_hostList.setObjectName("LV_hostList")
        self.gridLayout_2.addWidget(self.LV_hostList, 0, 0, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.RB_oneTimeTel = QtGui.QRadioButton(self.widget)
        self.RB_oneTimeTel.setCursor(QtCore.Qt.PointingHandCursor)
        self.RB_oneTimeTel.setChecked(True)
        self.RB_oneTimeTel.setObjectName("RB_oneTimeTel")
        self.verticalLayout.addWidget(self.RB_oneTimeTel)
        self.RB_batchTelnet = QtGui.QRadioButton(self.widget)
        self.RB_batchTelnet.setCursor(QtCore.Qt.PointingHandCursor)
        self.RB_batchTelnet.setObjectName("RB_batchTelnet")
        self.verticalLayout.addWidget(self.RB_batchTelnet)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.SB_pollCount = QtGui.QSpinBox(self.widget)
        self.SB_pollCount.setProperty("value", 1)
        self.SB_pollCount.setObjectName("SB_pollCount")
        self.gridLayout.addWidget(self.SB_pollCount, 0, 0, 1, 1)
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.SB_pollInterval = QtGui.QSpinBox(self.widget)
        self.SB_pollInterval.setProperty("value", 1)
        self.SB_pollInterval.setObjectName("SB_pollInterval")
        self.gridLayout.addWidget(self.SB_pollInterval, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.LCD_Counter = QtGui.QLCDNumber(self.widget)
        self.LCD_Counter.setObjectName("LCD_Counter")
        self.verticalLayout_2.addWidget(self.LCD_Counter)
        self.TxB_telnetPort = QtGui.QLineEdit(self.widget)
        self.TxB_telnetPort.setObjectName("TxB_telnetPort")
        self.verticalLayout_2.addWidget(self.TxB_telnetPort)
        self.TxB_telnetCommand = QtGui.QLineEdit(self.widget)
        self.TxB_telnetCommand.setObjectName("TxB_telnetCommand")
        self.verticalLayout_2.addWidget(self.TxB_telnetCommand)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BT_openFile = QtGui.QPushButton(self.widget)
        self.BT_openFile.setObjectName("BT_openFile")
        self.horizontalLayout.addWidget(self.BT_openFile)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.BT_cmdSend = QtGui.QPushButton(self.widget)
        self.BT_cmdSend.setEnabled(True)
        self.BT_cmdSend.setObjectName("BT_cmdSend")
        self.gridLayout_2.addWidget(self.BT_cmdSend, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.LV_logLines = QtGui.QListView(self.widget)
        self.LV_logLines.setMaximumSize(QtCore.QSize(301, 141))
        self.LV_logLines.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.LV_logLines.setObjectName("LV_logLines")
        self.gridLayout_3.addWidget(self.LV_logLines, 1, 0, 1, 1)

        self.retranslateUi(AppMainWindow)
        QtCore.QMetaObject.connectSlotsByName(AppMainWindow)
        AppMainWindow.setTabOrder(self.LV_hostList, self.RB_oneTimeTel)
        AppMainWindow.setTabOrder(self.RB_oneTimeTel, self.RB_batchTelnet)
        AppMainWindow.setTabOrder(self.RB_batchTelnet, self.SB_pollCount)
        AppMainWindow.setTabOrder(self.SB_pollCount, self.SB_pollInterval)
        AppMainWindow.setTabOrder(self.SB_pollInterval, self.TxB_telnetPort)
        AppMainWindow.setTabOrder(self.TxB_telnetPort, self.TxB_telnetCommand)
        AppMainWindow.setTabOrder(self.TxB_telnetCommand, self.BT_cmdSend)
        AppMainWindow.setTabOrder(self.BT_cmdSend, self.BT_openFile)
        AppMainWindow.setTabOrder(self.BT_openFile, self.LV_logLines)

    def retranslateUi(self, AppMainWindow):
        AppMainWindow.setWindowTitle(QtGui.QApplication.translate("AppMainWindow", "Telnet Asistant V1.1", None, QtGui.QApplication.UnicodeUTF8))
        self.RB_oneTimeTel.setText(QtGui.QApplication.translate("AppMainWindow", "One Time VPush", None, QtGui.QApplication.UnicodeUTF8))
        self.RB_batchTelnet.setText(QtGui.QApplication.translate("AppMainWindow", "Batch VPush", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("AppMainWindow", "Count               ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("AppMainWindow", "Interval", None, QtGui.QApplication.UnicodeUTF8))
        self.TxB_telnetPort.setPlaceholderText(QtGui.QApplication.translate("AppMainWindow", "Telnet PORT", None, QtGui.QApplication.UnicodeUTF8))
        self.TxB_telnetCommand.setPlaceholderText(QtGui.QApplication.translate("AppMainWindow", "Telnet Command", None, QtGui.QApplication.UnicodeUTF8))
        self.BT_openFile.setText(QtGui.QApplication.translate("AppMainWindow", "Select Host List", None, QtGui.QApplication.UnicodeUTF8))
        self.BT_cmdSend.setText(QtGui.QApplication.translate("AppMainWindow", "Send Command", None, QtGui.QApplication.UnicodeUTF8))

